### ISSUE TITLE
npm run build 失败

### ISSUE THREAD

**Issue by nyanboard** [giscafer/sinokit#1]
lerna ERR! npm run build stderr:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'json-templater/string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\work\single-spa-mobile\trunk\sinokit-master\packages\components\build\bin\build-entry.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE

**Comment by giscafer** [comment]
lerna 管理项目，先了解学习再使用。

报错原因：packages 包下没下载依赖。
